Repository falconry/falcon, pull requests merged in 2020-12, with the labels that each got.

#1769 feat(sink): allow matching sinks before or after static routes
  docs/_newsfragments/1372.newandimproved.rst
  falcon/app.py
  falcon/asgi/app.py
  falcon/inspect.py
  tests/test_inspect.py
  tests/test_sink_and_static.py
Labels: pr:prioritized

#1768 Normalize json dumps
  docs/_newsfragments/1767.breakingchange.rst
  docs/_newsfragments/1767.misc.rst
  docs/api/media.rst
  falcon/__init__.py
  falcon/app.py
  falcon/app_helpers.py
  falcon/asgi/__init__.py
  falcon/asgi/app.py
  falcon/asgi/structures.py
  falcon/http_error.py
  falcon/media/base.py
  falcon/media/handlers.py
  falcon/media/json.py
  falcon/request.py
  falcon/testing/client.py
  falcon/util/__init__.py
  tests/asgi/test_middleware_asgi.py
  tests/asgi/test_sse.py
  tests/test_custom_router.py
  tests/test_httperror.py
  tests/test_media_handlers.py
  tests/test_middleware.py
  tests/test_query_params.py
  tests/test_request_media.py
  tests/test_utils.py
Labels: pr:prioritized

#1764 refactor(Response): rename Response.body to Response.text
  README.rst
  docs/_newsfragments/1578.breakingchange.rst
  docs/_newsfragments/1679.breakingchange.rst
  docs/api/routing.rst
  docs/user/faq.rst
  docs/user/quickstart.rst
  docs/user/recipes/output-csv.rst
  docs/user/tutorial.rst
  examples/things.py
  examples/things_advanced.py
  examples/things_advanced_asgi.py
  examples/things_asgi.py
  falcon/app.py
  falcon/asgi/app.py
  falcon/asgi/response.py
  falcon/http_status.py
  falcon/response.py
  falcon/testing/resource.py
  tests/asgi/_asgi_test_app.py
  tests/asgi/test_example_asgi.py
  tests/asgi/test_hello_asgi.py
  tests/asgi/test_response_media_asgi.py
  tests/test_after_hooks.py
  tests/test_alias.py
  tests/test_app_initializers.py
  tests/test_before_hooks.py
  tests/test_cmd_inspect_app.py
  tests/test_cors_middleware.py
  tests/test_custom_router.py
  tests/test_default_router.py
  tests/test_error_handlers.py
  tests/test_example.py
  tests/test_headers.py
  tests/test_hello.py
  tests/test_http_method_routing.py
  tests/test_httperror.py
  tests/test_httpstatus.py
  tests/test_middleware.py
  tests/test_response_body.py
  tests/test_response_media.py
  tests/test_sink_and_static.py
  tests/test_testing.py
  tests/test_utils.py
  tests/test_wsgi.py
  tests/test_wsgiref_inputwrapper_with_size.py
Labels: pr:prioritized

#1758 fix(media): let media handlers deserialize empty media
  docs/_newsfragments/1589.breakingchange.rst
  docs/api/errors.rst
  docs/api/media.rst
  falcon/asgi/multipart.py
  falcon/asgi/request.py
  falcon/errors.py
  falcon/media/base.py
  falcon/media/json.py
  falcon/media/msgpack.py
  falcon/media/multipart.py
  falcon/media/urlencoded.py
  falcon/request.py
  falcon/testing/resource.py
  tests/test_httperror.py
  tests/test_media_multipart.py
  tests/test_media_urlencoded.py
  tests/test_request_media.py
Labels: pr:prioritized

#1737 docs(tutorial): port the ASGI tutorial
  .github/workflows/tests.yaml
  .gitignore
  docs/api/routing.rst
  docs/user/faq.rst
  docs/user/index.rst
  docs/user/tutorial-asgi.rst
  docs/user/tutorial.rst
  examples/asgilook/.coveragerc
  examples/asgilook/asgilook/__init__.py
  examples/asgilook/asgilook/app.py
  examples/asgilook/asgilook/asgi.py
  examples/asgilook/asgilook/cache.py
  examples/asgilook/asgilook/config.py
  examples/asgilook/asgilook/images.py
  examples/asgilook/asgilook/store.py
  examples/asgilook/requirements/asgilook
  examples/asgilook/requirements/test
  examples/asgilook/tests/__init__.py
  examples/asgilook/tests/conftest.py
  examples/asgilook/tests/test_images.py
  examples/asgilook/tests/test_thumbnails.py
  tox.ini
Labels: pr::prioritized

#1826 fix(App): cement the fact that body serialization error handling has been fixed
  docs/_newsfragments/1607.bugfix.rst
  tests/test_response_body.py
Labels: pr::prioritized

#1829 feat(App): validate that sink methods follow the app's concurrency model (when possible)
  falcon/app.py
  falcon/asgi/app.py
  tests/test_inspect.py
  tests/test_sinks.py
Labels: pr::prioritized

#1844 perf(ASGI): cythonize falcon.asgi module tree
  falcon/asgi/_asgi_helpers.py
  falcon/asgi/app.py
  setup.py
  tests/asgi/test_asgi_helpers.py
Labels: perf
